apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-service-dev.fullname" . }}-secret
type: Opaque
data:
  username: {{ .Values.secret.username | b64enc | quote }}
  password: {{ .Values.secret.password | b64enc | quote }}
